//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicReception
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public int RecordID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Phone { get; set; }
        public Nullable<int> MedCard { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Department { get; set; }
        public string DocSurname { get; set; }
        public string DocName { get; set; }
        public string DocPatronymic { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
