//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicReception
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicReceptionEntities : DbContext
    {
        private static ClinicReceptionEntities _context;
        public ClinicReceptionEntities()
            : base("name=ClinicReceptionEntities")
        {
        }

        public static ClinicReceptionEntities GetContext()
        {
            if (_context == null)
                _context = new ClinicReceptionEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<AppointmentRegistration> AppointmentRegistration { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<IncidenceReports> IncidenceReports { get; set; }
        public virtual DbSet<PatientInfo> PatientInfo { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WorkScopeReports> WorkScopeReports { get; set; }

    }
}
