//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicReception
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfo
    {
        public int PatientID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<int> MedCard { get; set; }
        public string Phone { get; set; }
        public string DocsObservations { get; set; }
        public string MedAppointments { get; set; }
        public string PrescribedTests { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
