//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicReception
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkScopeReports
    {
        public int ReportID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ReportType { get; set; }
        public Nullable<int> DocID { get; set; }
        public string DocSurname { get; set; }
        public string DocName { get; set; }
        public string DocPatronymic { get; set; }
        public string Department { get; set; }
        public Nullable<int> HoursWorked { get; set; }
        public Nullable<int> AppointmentsNum { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
